### ISSUE TITLE
No responding after AI name: xxx

### ISSUE THREAD

**Issue by RebelYoung** [Significant-Gravitas/AutoGPT#2124]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

I have set as Installation for Openai API and Google API.
However, there is no response after input the "AI name".

```python
(pycfd) D:\python\Auto-GPT>python -m autogpt --speak --gpt3only
Speak Mode:  ENABLED
GPT3.5 Only Mode:  ENABLED
Welcome to Auto-GPT!  Enter the name of your AI and its role Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.elevenlabs.io', port=443): Max retries exceeded with url: /v1/text-to-speech/your-voice-id-1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\python\Auto-GPT\autogpt\speech\say.py", line 34, in speak
below.     success = VOICE_ENGINE.say(text, voice_index)
  File "D:\python\Auto-GPT\autogpt\speech\base.py", line 33, in say
    return self._speech(text, voice_index)
  File "D:\python\Auto-GPT\autogpt\speech\eleven_labs.py", line 75, in _speech
Entering     response = requests.post(tts_url, headers=self._headers, json={"text": text})
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.elevenlabs.io', port=443): Max retries exceeded with url: /v1/text-to-speech/your-voice-id-1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))
nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: Tutor-GPT


```

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by RebelYoung** [comment]
```python
Goal 4: Using memory of type:  LocalCache Using Browser:  chrome Traceback (most recent call last):   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen     self._prepare_proxy(conn)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy     conn.connect()   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\connection.py", line 369, in connect     self.sock = conn = self._connect_tls_proxy(hostname, conn)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy     socket = ssl_wrap_socket(   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl     return ssl_context.wrap_socket(sock)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\ssl.py", line 500, in wrap_socket     return self.sslsocket_class._create(   File "C:\Users\Rebel\.conda\envs\pycfd\lib\ssl.py", line 1040, in _create     self.do_handshake()   File "C:\Users\Rebel\.conda\envs\pycfd\lib\ssl.py", line 1309, in do_handshake     self._sslobj.do_handshake() ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\adapters.py", line 489, in send     resp = conn.urlopen(   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen     retries = retries.increment(   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\urllib3\util\retry.py", line 592, in increment     raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "C:\Users\Rebel\.conda\envs\pycfd\lib\runpy.py", line 194, in _run_module_as_main     return _run_code(code, main_globals, None,   File "C:\Users\Rebel\.conda\envs\pycfd\lib\runpy.py", line 87, in _run_code     exec(code, run_globals)   File "D:\python\Auto-GPT\autogpt\__main__.py", line 50, in <module>     main()   File "D:\python\Auto-GPT\autogpt\__main__.py", line 46, in main     agent.start_interaction_loop()   File "D:\python\Auto-GPT\autogpt\agent\agent.py", line 75, in start_interaction_loop     assistant_reply = chat_with_ai(   File "D:\python\Auto-GPT\autogpt\chat.py", line 95, in chat_with_ai     ) = generate_context(prompt, relevant_memory, full_message_history, model)   File "D:\python\Auto-GPT\autogpt\chat.py", line 43, in generate_context     current_tokens_used = token_counter.count_message_tokens(current_context, model)   File "D:\python\Auto-GPT\autogpt\token_counter.py", line 25, in count_message_tokens     encoding = tiktoken.encoding_for_model(model)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model     return get_encoding(encoding_name)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\tiktoken\registry.py", line 63, in get_encoding     enc = Encoding(**constructor())   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base     mergeable_ranks = load_tiktoken_bpe(   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\tiktoken\load.py", line 114, in load_tiktoken_bpe     contents = read_file_cached(tiktoken_bpe_file)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\tiktoken\load.py", line 46, in read_file_cached     contents = read_file(blobpath)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\tiktoken\load.py", line 24, in read_file     return requests.get(blobpath).content   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\api.py", line 73, in get     return request("get", url, params=params, **kwargs)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\api.py", line 59, in request     return session.request(method=method, url=url, **kwargs)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\sessions.py", line 587, in request     resp = self.send(prep, **send_kwargs)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\sessions.py", line 701, in send     r = adapter.send(request, **kwargs)   File "C:\Users\Rebel\.conda\envs\pycfd\lib\site-packages\requests\adapters.py", line 563, in send     raise SSLError(e, request=request) requests.exceptions.SSLError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))
```

**Comment by USTBVEO** [comment]
The same problem with you. Hope for new responses or solutions from you

**Comment by RebelYoung** [comment]
> 

The solution is add a line in google_search.py
```
os.environ['ALL_PROXY']='http://127.0.0.1:7890'
```

**Comment by RebelYoung** [comment]
> The same problem with you. Hope for new responses or solutions from you

add your local ip and port in this line.

**Comment by ntindle** [comment]
Did this fix for you @RebelYoung?

**Comment by RebelYoung** [comment]
> 



> Did this fix for you @RebelYoung?

In my last one reply.

**Comment by USTBVEO** [comment]
您发给我的信件已收到。from Wei Yang/杨威
 
   This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by USTBVEO** [comment]
您发给我的信件已收到。from Wei Yang/杨威
 
   This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by USTBVEO** [comment]
您发给我的信件已收到。from Wei Yang/杨威
 
   This is an automatic reply, confirming that your e-mail was received.Thank you
