### ISSUE TITLE
prompt_toolkit.output.win32.NoConsoleScreenBufferError

### ISSUE THREAD

**Issue by sunshinecf** [Significant-Gravitas/AutoGPT#4753]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

An error occurs when attempting to debug running the __main__.py file,
I ran this project in the PyCharm editor，
How should I solve this problem，
Asking for advice. Thank you very much，
Operating environment：windows、python3.11.3  
...........................................................................................................................................................................................................................................................
Errors are as follows：
Traceback (most recent call last):
  File "F:\python\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "F:\python\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "F:\python\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\python_project\Auto-GPT\autogpt\cli.py", line 93, in main
    from autogpt.main import run_auto_gpt
  File "G:\python_project\Auto-GPT\autogpt\main.py", line 8, in <module>
    from autogpt.agent import Agent
  File "G:\python_project\Auto-GPT\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "G:\python_project\Auto-GPT\autogpt\agent\agent.py", line 26, in <module>
    from autogpt.memory.vector import VectorMemory
  File "G:\python_project\Auto-GPT\autogpt\memory\vector\__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
  File "G:\python_project\Auto-GPT\autogpt\memory\vector\memory_item.py", line 13, in <module>
    from autogpt.processing.text import chunk_content, split_text, summarize_text
  File "G:\python_project\Auto-GPT\autogpt\processing\text.py", line 13, in <module>
    from autogpt.utils import batch
  File "G:\python_project\Auto-GPT\autogpt\utils.py", line 14, in <module>
    session = PromptSession(history=InMemoryHistory())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 477, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 728, in _create_application
    application: Application[_T] = Application(
                                   ^^^^^^^^^^^^
  File "F:\python\Lib\site-packages\prompt_toolkit\application\application.py", line 273, in __init__
    self.output = output or session.output
                            ^^^^^^^^^^^^^^
  File "F:\python\Lib\site-packages\prompt_toolkit\application\current.py", line 68, in output
    self._output = create_output()
                   ^^^^^^^^^^^^^^^
  File "F:\python\Lib\site-packages\prompt_toolkit\output\defaults.py", line 87, in create_output
    return Win32Output(stdout, default_color_depth=color_depth_from_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python\Lib\site-packages\prompt_toolkit\output\win32.py", line 116, in __init__
    info = self.get_win32_screen_buffer_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python\Lib\site-packages\prompt_toolkit\output\win32.py", line 220, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?
The final debug executes until the code is finished:win32.py raise NoConsoleScreenBufferError

### Upload Activity Log Content

1

### Upload Error Log Content

1

**Comment by sunshinecf** [comment]
win32.py  error occurred

**Comment by Glitch-art** [comment]
Hello!.
I have a similar error, only it happens when I'm running 'pytest'
