### ISSUE TITLE
TypeError: 'numpy._DTypeMeta' object is not subscriptable

### ISSUE THREAD

**Issue by sugoides** [Significant-Gravitas/AutoGPT#4850]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Got this error
```
C:\Bot\Auto-GPT-0.4.3>python -m autogpt
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\cli.py", line 93, in main
    from autogpt.main import run_auto_gpt
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\main.py", line 7, in <module>
    from autogpt.agent import Agent
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\agent\agent.py", line 22, in <module>
    from autogpt.memory.vector import VectorMemory
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\memory\vector\__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\memory\vector\memory_item.py", line 15, in <module>
    from .utils import Embedding, get_embedding
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\memory\vector\utils.py", line 10, in <module>
    Embedding = list[np.float32] | np.ndarray[Any, np.dtype[np.float32]]
TypeError: 'numpy._DTypeMeta' object is not subscriptable
```

**Comment by sugoides** [comment]
I've updated to latest stable release of python and now got this error

```
C:\Bot\Auto-GPT-0.4.3>python -m autogpt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Python\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\cli.py", line 93, in main
    from autogpt.main import run_auto_gpt
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\main.py", line 7, in <module>
    from autogpt.agent import Agent
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\agent\agent.py", line 11, in <module>
    from autogpt.llm.chat import chat_with_ai
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\llm\chat.py", line 14, in <module>
    from autogpt.llm.utils import count_message_tokens, create_chat_completion
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\llm\utils\__init__.py", line 19, in <module>
    from .token_counter import *
  File "C:\Bot\Auto-GPT-0.4.3\autogpt\llm\utils\token_counter.py", line 6, in <module>
    import tiktoken
  File "C:\Python\Lib\site-packages\tiktoken\__init__.py", line 1, in <module>
    from .core import Encoding as Encoding
  File "C:\Python\Lib\site-packages\tiktoken\core.py", line 7, in <module>
    import regex
  File "C:\Python\Lib\site-packages\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Python\Lib\site-packages\regex\regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "C:\Python\Lib\site-packages\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'
```

**Comment by ai-naymul** [comment]
Hey @sugoides did you installed the `regex` module if not try install by following command:
`pip install regex`
and run it again

**Comment by nixfred** [comment]
Im still getting this error after installing regex, any ideas?

i@mintop:~/Auto-GPT$ ./run.sh
All packages are installed.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/pi/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/home/pi/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/pi/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/Auto-GPT/autogpt/cli.py", line 114, in main
    from autogpt.main import run_auto_gpt
  File "/home/pi/Auto-GPT/autogpt/main.py", line 9, in <module>
    from autogpt.agents import Agent
  File "/home/pi/Auto-GPT/autogpt/agents/__init__.py", line 1, in <module>
    from .agent import Agent
  File "/home/pi/Auto-GPT/autogpt/agents/agent.py", line 26, in <module>
    from autogpt.memory.vector import VectorMemory
  File "/home/pi/Auto-GPT/autogpt/memory/vector/__init__.py", line 4, in <module>
    from .memory_item import MemoryItem, MemoryItemRelevance
  File "/home/pi/Auto-GPT/autogpt/memory/vector/memory_item.py", line 15, in <module>
    from .utils import Embedding, get_embedding
  File "/home/pi/Auto-GPT/autogpt/memory/vector/utils.py", line 10, in <module>
    Embedding = list[np.float32] | np.ndarray[Any, np.dtype[np.float32]]
TypeError: 'numpy._DTypeMeta' object is not subscriptable
Press any key to continue...

**Comment by Stefan-Wagner** [comment]
I got the same error on Linux as in the first message: "TypeError: 'numpy._DTypeMeta' object is not subscriptable"

System is: "Ubuntu 22.04.3 LTS"
kernel 6.2.0-26-generic
Python is Python 3.10.12
pip 23.2.1 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)

I don't know Python but tried some hints from StackOverflow, namely wrapping the RHS in Apostrophes, as well as pip-installing regex to no success. Still not subscriptable., 

I'm trying to run 
> python3 -m autogpt --gpt3only
