### ISSUE TITLE
execute python is glitching

### ISSUE THREAD

**Issue by jmikedupont2** [Significant-Gravitas/AutoGPT#5354]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

```2023-09-27 10:39:29,432 INFO  Executing python file '/workspaces/Auto-GPT/autogpts/autogpt/auto_gpt_workspace\
/.s/Auto-GPT/autogpts/autogpt/auto_gpt_workspace/tmpcz0gyaxn.py' in working directory '/workspaces/Auto-GPT/a\
utogpts/autogpt/auto_gpt_workspace'
AGENT ERRR python: can't open file '/workspaces/Auto-GPT/autogpts/autogpt/auto_gpt_workspace/.s/Auto-GPT/auto\
gpts/autogpt/auto_gpt_workspace/tmpcz0gyaxn.py': [Errno 2] No such file or directory
AGENT ERRR python: can't open file '/workspaces/Auto-GPT/autogpts/autogpt/auto_gpt_workspace/.s/Auto-GPT/auto\
gpts/autogpt/auto_gpt_workspace/tmpcz0gyaxn.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/workspaces/Auto-GPT/autogpts/autogpt/autogpt/commands/execute_code.py", line 65, in execute_python_c\
ode
    return execute_python_file(tmp_code_file.name, agent)
  File "/workspaces/Auto-GPT/autogpts/autogpt/autogpt/command_decorator.py", line 56, in wrapper                  return func(*args, **kwargs)                                                                                File "/workspaces/Auto-GPT/autogpts/autogpt/autogpt/commands/decorators.py", line 73, in wrapper                return func(*args, **kwargs)
  File "/workspaces/Auto-GPT/autogpts/autogpt/autogpt/commands/execute_code.py", line 115, in execute_python_```

### Upload Activity Log Content

_No response_

### Upload Error Log Content

_No response_

**Comment by ozzymuppet** [comment]
Same...

**Comment by jmikedupont2** [comment]
I dont have this in my lastest update. what version are you on?

**Comment by jmikedupont2** [comment]
I have it fixed after rebasing https://twitter.com/introsp3ctor/status/1708301615143256165?t=fuwFrgIAd7uZixTVZKfK6A&s=19
