### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by ddigitech** [Significant-Gravitas/AutoGPT#5631]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Traceback (most recent call last):
  File "/root/projects/DAutoGPT/cli.py", line 883, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/DAutoGPT/cli.py", line 129, in setup
    if "public_repo" in scopes or "repo" in scopes:
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
root@dh-kub:~/projects/DAutoGPT#

### Upload Error Log Content

Traceback (most recent call last):
  File "/root/projects/DAutoGPT/cli.py", line 883, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/DAutoGPT/cli.py", line 129, in setup
    if "public_repo" in scopes or "repo" in scopes:
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
root@dh-kub:~/projects/DAutoGPT#

**Comment by bradley** [comment]
I had the same issue. I think you probably created a GitHub access token using the beta version and not the classic version. Delete that access token and re-make one, but be sure to click `Generate new token (classic)` when doing so, and give it "repo" access.

**Comment by Rollesy** [comment]
I kept clicking on classic token and then choosing beta thinking it was the scope and repo the system kept mentioning but it is just the classic token you need.

**Comment by Rollesy** [comment]
> This issue was closed automatically because it has been stale for 10 days with no activity.

stop telling people to choose the token with repo and and scope and just say classic ya twat.
