### ISSUE TITLE
Setup Error: "OSError: [WinError 193] %1 is not a valid Win32 application"

### ISSUE THREAD

**Issue by lennart02** [Significant-Gravitas/AutoGPT#5708]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

When I try to setup the project I got a "OSError: [WinError 193] %1 is not a valid Win32 application" error. I have no clue where this should come from. I executed the command `./run setup` on the top level root of the \Auto-GPT\ repo.
I tried various things like:
- reinstalling python
- clearing my windows environment variables
- clearing my \AppData\Roaming\Python\ from old installation

Other information:
- I am using Windows 10 64 bit
- Python 3.11.6

### Upload Error Log Content

$ ./run setup

🚀 Setup initiated...

None C:\Users\lenna\Programmierung\repos\Auto-GPT\setup.sh
Traceback (most recent call last):
  File "C:\Users\lenna\Programmierung\repos\Auto-GPT\cli.py", line 891, in <module>
    cli()
  File "C:\Users\lenna\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenna\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\lenna\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenna\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenna\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenna\Programmierung\repos\Auto-GPT\cli.py", line 52, in setup
    subprocess.check_call([setup_script], cwd=script_dir)
  File "C:\Users\lenna\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenna\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenna\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\lenna\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1539, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by Jianhao9698** [comment]
I have this issue too

**Comment by ylylaaaa** [comment]
me too

**Comment by ylylaaaa** [comment]
how to solve this ,thanks

**Comment by HiJim** [comment]
Me too facing this issue on Windows. Looks like AutoGPT is tested on Linux only :-(

**Comment by HiJim** [comment]
Same problem, I am using Python 3.11.4

**Comment by Bentlybro** [comment]
it is recomended to use WSL to run AutoGPT, check here to see what WSL is https://learn.microsoft.com/en-us/windows/wsl/install

and here is the latest up to date docs that mention using WSL https://docs.agpt.co/autogpt/setup/#windows-wsl

**Comment by nauen** [comment]
Issue still exist, WSL is not working eather. Why the tool is changed, that its not installable anymore?

`D:\AutoGPT\AutoGPT>python3 cli.py "$@"
Der Befehl "python3" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

D:\AutoGPT\AutoGPT>./cli.py
Der Befehl "." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

D:\AutoGPT\AutoGPT>python cli.py
Usage: cli.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  agent      Commands to create, start and stop agents
  benchmark  Commands to start the benchmark and list tests and categories
  setup      Installs dependencies needed for your system.

D:\AutoGPT\AutoGPT>python cli.py setup

       d8888          888             .d8888b.  8888888b. 88888888888
      d88888          888            d88P  Y88b 888   Y88b    888
     d88P888          888            888    888 888    888    888
    d88P 888 888  888 888888 .d88b.  888        888   d88P    888
   d88P  888 888  888 888   d88""88b 888  88888 8888888P"     888
  d88P   888 888  888 888   888  888 888    888 888           888
 d8888888888 Y88b 888 Y88b. Y88..88P Y88b  d88P 888           888
d88P     888  "Y88888  "Y888 "Y88P"   "Y8888P88 888           888
                                                                                                                        

🚀 Setup initiated...

Traceback (most recent call last):
  File "D:\AutoGPT\AutoGPT\cli.py", line 501, in <module>
    cli()
  File "C:\Users\paul\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\paul\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\paul\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\paul\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\paul\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\AutoGPT\AutoGPT\cli.py", line 50, in setup
    subprocess.check_call([setup_script], cwd=script_dir)
  File "C:\Users\paul\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\paul\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\paul\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\paul\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung

D:\AutoGPT\AutoGPT>`

**Comment by Alejandro1234-bit** [comment]
Hello i have this same problem 

Traceback (most recent call last):
  File "C:\Users\aguerrico\PycharmProjects\Web Scrapping\chromedriver-win32\DISCO UY.py", line 121, in <module>
    product_details = scrape_disco_products(urls)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aguerrico\PycharmProjects\Web Scrapping\chromedriver-win32\DISCO UY.py", line 18, in scrape_disco_products
    driver = webdriver.Chrome(service=service)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aguerrico\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\aguerrico\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 55, in __init__
    self.service.start()
  File "C:\Users\aguerrico\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self._start_process(self._path)
  File "C:\Users\aguerrico\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\service.py", line 208, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\aguerrico\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\aguerrico\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 no es una aplicación Win32 válida

Any recomendations to fix it?

Thank you in advance!
