### ISSUE TITLE
Installing Poetry (1.6.1): Creating environment

### ISSUE THREAD

**Issue by omidshz100** [Significant-Gravitas/AutoGPT#5838]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

after I use this command ./run setup , I have this issue

### Upload Activity Log Content

Installing Poetry (1.6.1): Creating environment
Traceback (most recent call last):
  File "<stdin>", line 945, in <module>
  File "<stdin>", line 923, in main
  File "<stdin>", line 560, in run
  File "<stdin>", line 581, in install
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "<stdin>", line 653, in make_env
  File "<stdin>", line 639, in make_env
  File "<stdin>", line 317, in make
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/venv/__init__.py", line 66, in __init__
    self.symlinks = should_use_symlinks(symlinks)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/venv/__init__.py", line 31, in should_use_symlinks
    raise Exception("This build of python cannot create venvs without using symlinks")
Exception: This build of python cannot create venvs without using symlinks
❌ There was an issue with the installation.
✅ GitHub account is configured with username: Omid Shojaeian Zanjani and email: 46863450+omidshz100@users.noreply.github.com
✅ GitHub access token loaded successfully.
✅ GitHub access token has the required permissions.

### Upload Error Log Content

Exception: This build of python cannot create venvs without using symlinks
❌ There was an issue with the installation.

**Comment by jianglonghui** [comment]
it occurs to me too. Have you ever solved it?

**Comment by jianglonghui** [comment]
oh, I succeed to solve it by reinstall python by "brew install python"

**Comment by simuler** [comment]
oh, I succeed to solve it by "pip3 install poetry",i hope you can try it

**Comment by heaversm** [comment]
Didn

> oh, I succeed to solve it by "pip3 install poetry",i hope you can try it

Didn't work for me.

**Comment by Cedric1024** [comment]
> oh, I succeed to solve it by reinstall python by "brew install python"

I succeed to solve it too. It works. Thank you.

**Comment by tushanFox** [comment]
> oh, I succeed to solve it by "pip3 install poetry",i hope you can try it

me too.

**Comment by ntindle** [comment]
@omidshz100 did you install via brew?
