### ISSUE TITLE
The ability returned from ChatGPT3.5 is not in the registered abilities in autogpt sdk?

### ISSUE THREAD

**Issue by stargatejy** [Significant-Gravitas/AutoGPT#5988]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Other

### Describe your issue.

"design_product" ability is not defined or registered in \sdk\abilities, but GPT3.5 return it which cause code return error.

### Upload Error Log Content

[2023-10-27 12:13:24,415] [forge.agent ] [INFO] 📝 {'ability': {'args': {'product': 'glass', 'target_audience': 'older adults'},
'name': 'design_product'},
'thoughts': {'criticism': 'The glass design should consider the individual '
'needs and preferences of older adults. It is '
'important to gather feedback from users and make '
'iterative improvements.',
'plan': '- Ensure the glass is durable and shatterproof\n'
'- Make the glass lightweight to reduce the risk of '
'dropping\n'
'- Include a non-slip grip or textured surface for '
'better handling\n'
'- Avoid sharp edges or protrusions\n'
'- Provide a wide base for stability\n'
'- Consider adding measurements for portion control and '
'dietary needs\n'
'- Opt for a larger, ergonomic handle for easier '
'grasping\n'
'- Use transparent materials to easily see the contents\n'
'- Consider a spill-proof lid or straw option\n'
'- Test the design with older adults for feedback and '
'improvements',
'reasoning': 'Older adults often face specific challenges when '
'it comes to using glassware. The design should '
'prioritize safety, ease of use, and comfort.',
'speak': 'I have thought of a design for a glass that addresses '
'the specific needs of older adults. It prioritizes '
'safety, ease of use, and comfort.',
'text': 'Designing a glass for old man'}}
[2023-10-27 12:13:24,415] [forge.agent ] [INFO] 📝 design_product
[2023-10-27 12:13:24,416] [forge.sdk.routes.agent_protocol] [ERROR] ❌ Error whilst trying to execute a task step: 19a77845-86bd-430c-a28d-d0af52c0f95e
Traceback (most recent call last):
File "/Users/a1234/autogpt-test/MangoAI/autogpts/MangoAgent-3/forge/sdk/routes/agent_protocol.py", line 358, in execute_agent_task_step
step = await agent.execute_step(task_id, step)
File "/Users/a1234/autogpt-test/MangoAI/autogpts/MangoAgent-3/forge/agent.py", line 214, in execute_step
output = await self.abilities.run_ability(
File "/Users/a1234/autogpt-test/MangoAI/autogpts/MangoAgent-3/forge/sdk/abilities/registry.py", line 187, in run_ability
ability = self.abilities[ability_name]
KeyError: 'design_product'

**Comment by stargatejy** [comment]
sometimes the ability returned by GPT3.5 is "speak" which is not an ability, it is so strange which the system promote has clearly told GPT to call the ability which is registered in SDK/abilities
