### ISSUE TITLE
`generate_agent_profile_for_task` fails

### ISSUE THREAD

**Issue by egeres** [Significant-Gravitas/AutoGPT#6050]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

- System: `WSL`
- Python: `3.11.5`
- HEAD commit: `fc1d73ba60a4c0554bc6d1085c4085228399d359`

After installing the project manually with poetry on a separate conda environment, I attempt to run `./run.sh run` at the dir `/AutoGPT/autogpts/autogpt`, my `/AutoGPT/autogpts/autogpt/data` is empty at the time of execution, but it fails to run `await generate_agent_profile_for_task`

I have checked `autogpts/autogpt/logs/error.log` but it's empty, I think mainly because the issue happens at a library level, I'm not sure. I think instead I should paste the log of the terminal directly

```
$ ./run.sh run
2023-10-31 13:28:55,022 INFO  NEWS: Welcome to AutoGPT!
2023-10-31 13:28:55,025 INFO  NEWS: Below you'll find the latest AutoGPT News and updates regarding features!
2023-10-31 13:28:55,027 INFO  NEWS: If you don't wish to see this message, you can run AutoGPT with the --skip-news flag.
2023-10-31 13:28:55,028 INFO  NEWS:
2023-10-31 13:28:55,030 INFO  NEWS: QUICK LINKS 🔗
2023-10-31 13:28:55,031 INFO  NEWS: --------------
2023-10-31 13:28:55,033 INFO  NEWS: 🌎 Official Website: https://agpt.co.
2023-10-31 13:28:55,035 INFO  NEWS: 📖 User Guide: https://docs.agpt.co.
2023-10-31 13:28:55,037 INFO  NEWS: 👩 Contributors Wiki: https://github.com/Significant-Gravitas/Nexus/wiki/Contributing.
2023-10-31 13:28:55,038 INFO  NEWS:
2023-10-31 13:28:55,040 INFO  NEWS: v0.4.7 RELEASE HIGHLIGHTS! 🚀
2023-10-31 13:28:55,041 INFO  NEWS: -----------------------------
2023-10-31 13:28:55,043 INFO  NEWS: This release introduces initial REST API support, powered by e2b's agent
2023-10-31 13:28:55,044 INFO  NEWS: protocol SDK (https://github.com/e2b-dev/agent-protocol#sdk).
2023-10-31 13:28:55,046 INFO  NEWS:
2023-10-31 13:28:55,047 INFO  NEWS: It also includes improvements to prompt generation and support
2023-10-31 13:28:55,049 INFO  NEWS: for our new benchmarking tool, Auto-GPT-Benchmarks
2023-10-31 13:28:55,050 INFO  NEWS: (https://github.com/Significant-Gravitas/Auto-GPT-Benchmarks).
2023-10-31 13:28:55,052 INFO  NEWS:
2023-10-31 13:28:55,053 INFO  NEWS: We've also moved our documentation to Material Theme, at https://docs.agpt.co.
2023-10-31 13:28:55,055 INFO  NEWS:
2023-10-31 13:28:55,056 INFO  NEWS: As usual, we've squashed a few bugs and made some under-the-hood improvements.
2023-10-31 13:28:55,057 INFO  NEWS:
2023-10-31 13:28:55,059 INFO  NEWS: Take a look at the Release Notes on Github for the full changelog:
2023-10-31 13:28:55,060 INFO  NEWS: https://github.com/Significant-Gravitas/AutoGPT/releases.
2023-10-31 13:28:55,062 INFO  NEWS:
Enter the task that you want AutoGPT to execute, with as much detail as possible: Help me do stuff
2023-10-31 13:29:26,338 INFO  message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=7019 request_id=b74d900e3f2d7232c9b2666ab09f9be3 response_code=200
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/c/Github/AutoGPT/autogpts/autogpt/autogpt/__main__.py", line 5, in <module>
    autogpt.app.cli.cli()
  File "/home/cherrypie/miniconda3/envs/autogpt/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cherrypie/miniconda3/envs/autogpt/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/cherrypie/miniconda3/envs/autogpt/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cherrypie/miniconda3/envs/autogpt/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cherrypie/miniconda3/envs/autogpt/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Github/AutoGPT/autogpts/autogpt/autogpt/app/cli.py", line 159, in run
    run_auto_gpt(
  File "/mnt/c/Github/AutoGPT/autogpts/autogpt/autogpt/core/runner/client_lib/utils.py", line 59, in wrapper
    return asyncio.run(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cherrypie/miniconda3/envs/autogpt/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/cherrypie/miniconda3/envs/autogpt/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cherrypie/miniconda3/envs/autogpt/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/mnt/c/Github/AutoGPT/autogpts/autogpt/autogpt/app/main.py", line 215, in run_auto_gpt
    ai_profile, task_oriented_ai_directives = await generate_agent_profile_for_task(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Github/AutoGPT/autogpts/autogpt/autogpt/agent_factory/profile_generator.py", line 209, in generate_agent_profile_for_task
    await llm_provider.create_chat_completion(
  File "/mnt/c/Github/AutoGPT/autogpts/autogpt/autogpt/core/resource/model_providers/openai.py", line 291, in create_chat_completion
    response_message["function_call"] = _functions_compat_extract_call(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Github/AutoGPT/autogpts/autogpt/autogpt/core/resource/model_providers/openai.py", line 603, in _functions_compat_extract_call
    raise ValueError("Could not find function call block in response")
ValueError: Could not find function call block in response
```

**Comment by Pwuts** [comment]
Should be resolved since we switched the default model to `gpt-4` (from `gpt-4-0314`).

Using older models that don't have a native function calling interface, it will do this sometimes, because our function calling compatibility layer isn't perfect.
