### ISSUE TITLE
Cannot use Azure OpenAI api

### ISSUE THREAD

**Issue by justanyone2023** [Significant-Gravitas/AutoGPT#6408]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

When I use Azure OpenAI api to run the autoGPT as https://gist.github.com/primaryobjects/523577860628974501ffd3c52cd73525, but failed in authentication. I have checked the OPENAI_API_KEY and azure.yaml.  So the reason is that Azure is not supported anymore?

### Upload Error Log Content

(base) bifenglin@bifenglindeMacBook-Pro AutoDocker % docker compose run --rm auto-gpt
  plugins_config.yaml does not exist, creating base config.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.app.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/app/cli.py", line 121, in main
    run_auto_gpt(
  File "/app/autogpt/app/main.py", line 70, in run_auto_gpt
    create_config(
  File "/app/autogpt/app/configurator.py", line 99, in create_config
    config.fast_llm = check_model(config.fast_llm, "fast_llm", config=config)
  File "/app/autogpt/app/configurator.py", line 176, in check_model
    models = api_manager.get_models(**openai_credentials)
  File "/app/autogpt/llm/api_manager.py", line 107, in get_models
    all_models = openai.Model.list(**openai_credentials)["data"]
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/listable_api_resource.py", line 60, in list
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Your authentication token is not from a valid issuer.

**Comment by Pwuts** [comment]
Should be fixed in #6497. Please test and let me know :)
