### ISSUE TITLE
 ./run agent start autogpt

### ISSUE THREAD

**Issue by olariuromeo** [Significant-Gravitas/AutoGPT#6517]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

 ./run agent start autogpt
./run: 3: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home//miniconda3/envs/autogpt/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/apps/AutoGPT/autogpts/autogpt/autogpt/app/cli.py", line 8, in <module>
    from autogpt.logs.config import LogFormatName
  File "/home/apps/AutoGPT/autogpts/autogpt/autogpt/logs/__init__.py", line 1, in <module>
    from .config import configure_chat_plugins, configure_logging
  File "/home/apps/AutoGPT/autogpts/autogpt/autogpt/logs/config.py", line 12, in <module>
    from openai.util import logger as openai_logger
ModuleNotFoundError: No module named 'openai.util'

**Comment by monsieurcasquette** [comment]
i have this problem two

**Comment by ErikLorenzo** [comment]
me 2 now :(

**Comment by Thinking80s** [comment]
+1

**Comment by Nubebuster** [comment]
me too
