### ISSUE TITLE
azure integration bug that add an extra / to the url endpoint

### ISSUE THREAD

**Issue by JiewenGuan** [Significant-Gravitas/AutoGPT#6519]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I have successfully set up the web ui of this project, but when I entered my first prompt the backend throws an error(listed in the activity log and error log session)

I think the problem is that it supposed to be only one / before the "openai/deployments..." but there is two. I tried to locate where is the second / added but I cannot. 

### Upload Activity Log Content

2023-12-07 06:39:04,785 DEBUG  Creating agent for task: '[my prompt]'
2023-12-07 06:39:05,849 INFO  message='OpenAI API response' path=https://[myservice].openai.azure.com//openai/deployments/[mydeploy]/chat/completions?api-version=2023-07-01-preview processing_ms=None request_id=[reqid] response_code=400
2023-12-07 06:39:05,849 INFO  error_code=None error_message='Unrecognized request arguments supplied: tool_choice, tools' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-12-07 06:39:05,849] [forge.sdk.routes.agent_protocol] [ERROR]     ❌  Error whilst trying to create a task: input='[my prompt]' additional_input=None

### Upload Error Log Content

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/agpt-lFQuq64d-py3.10/lib/python3.10/site-packages/forge/sdk/routes/agent_protocol.py", line 86, in create_agent_task
    task_request = await agent.create_task(task_request)
  File "/home/user/repo/AutoGPT/autogpts/autogpt/autogpt/app/agent_protocol_server.py", line 115, in create_task
    task_agent = await generate_agent_for_task(
  File "/home/user/repo/AutoGPT/autogpts/autogpt/autogpt/agent_factory/generators.py", line 20, in generate_agent_for_task
    ai_profile, task_directives = await generate_agent_profile_for_task(
  File "/home/user/repo/AutoGPT/autogpts/autogpt/autogpt/agent_factory/profile_generator.py", line 237, in generate_agent_profile_for_task
    await llm_provider.create_chat_completion(
  File "/home/user/repo/AutoGPT/autogpts/autogpt/autogpt/core/resource/model_providers/openai.py", line 367, in create_chat_completion
    response = await self._create_chat_completion(
  File "/home/user/repo/AutoGPT/autogpts/autogpt/autogpt/core/resource/model_providers/openai.py", line 561, in _wrapped
    return await func(*args, **kwargs)
  File "/home/user/repo/AutoGPT/autogpts/autogpt/autogpt/core/resource/model_providers/openai.py", line 510, in _create_chat_completion
    return await openai.ChatCompletion.acreate(
  File "/home/user/.cache/pypoetry/virtualenvs/agpt-lFQuq64d-py3.10/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/agpt-lFQuq64d-py3.10/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/home/user/.cache/pypoetry/virtualenvs/agpt-lFQuq64d-py3.10/lib/python3.10/site-packages/openai/api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "/home/user/.cache/pypoetry/virtualenvs/agpt-lFQuq64d-py3.10/lib/python3.10/site-packages/openai/api_requestor.py", line 728, in _interpret_async_response
    self._interpret_response_line(
  File "/home/user/.cache/pypoetry/virtualenvs/agpt-lFQuq64d-py3.10/lib/python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request arguments supplied: tool_choice, tools`

**Comment by Marks13** [comment]
Same behavior there, thanks for the hotfix.
