### ISSUE TITLE
Docker: No module named 'auto_gpt_plugin_template'

### ISSUE THREAD

**Issue by amittos** [Significant-Gravitas/AutoGPT#6566]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I'm trying to run the Docker version of AutoGPT using v0.5. When I run `docker compose run --rm auto-gpt` I get the following error: 

```
[+] Running 1/0
 ✔ Network autogpt_default  Created                                                                                          0.0s 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/autogpt/app/cli.py", line 8, in <module>
    from autogpt.logs.config import LogFormatName
  File "/app/autogpt/logs/__init__.py", line 1, in <module>
    from .config import configure_chat_plugins, configure_logging
  File "/app/autogpt/logs/config.py", line 11, in <module>
    from auto_gpt_plugin_template import AutoGPTPluginTemplate
ModuleNotFoundError: No module named 'auto_gpt_plugin_template'
```

**Comment by Pwuts** [comment]
I've pushed out a new build for v0.5.0, the issue should be fixed. Thanks for reporting this!
