### ISSUE TITLE
Python library error

### ISSUE THREAD

**Issue by bhsbhs235** [Significant-Gravitas/AutoGPT#6677]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Agents

### Describe your issue.

python --version
3.10.11

pip -V
pip 23.3.2 from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)

poetry -V
Poetry (version 1.7.1)

./autogpt.sh  run

### Upload Activity Log Content

Missing packages:
auto-gpt-plugin-template (*) @ git+https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template@0.1.0, autogpt-forge (*) @ git+https://github.com/Significant-Gravitas/AutoGPT.git#subdirectory=autogpts/forge, beautifulsoup4 (>=4.12.2,<5.0.0), boto3 (>=1.33.6,<2.0.0), distro (>=1.8.0,<2.0.0), docker, duckduckgo-search (>=4.0.0,<5.0.0), en-core-web-sm (*) @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl, fastapi, ftfy (>=6.1.1,<7.0.0), gitpython (>=3.1.32,<4.0.0), google-api-python-client, gTTS (>=2.3.1,<3.0.0), hypercorn (>=0.14.4,<0.15.0), inflection, jsonschema, openai (>=0.27.10,<0.28.0), orjson (>=3.8.10,<4.0.0), Pillow, pinecone-client (>=2.2.1,<3.0.0), playsound (>=1.2.2,<1.3.0), prompt_toolkit (>=3.0.38,<4.0.0), pydantic, pylatexenc, pypdf (>=3.1.0,<4.0.0), python-docx, python-dotenv (>=1.0.0,<2.0.0), readability-lxml (>=0.8.1,<0.9.0), redis, selenium (>=4.11.2,<5.0.0), spacy (>=3.0.0,<4.0.0), tiktoken (>=0.5.0,<0.6.0), webdriver-manager, openapi-python-client (>=0.14.0,<0.15.0), google-cloud-logging (>=3.8.0,<4.0.0), google-cloud-storage (>=2.13.0,<3.0.0), psycopg2-binary (>=2.9.9,<3.0.0)

Installing dependencies from lock file

No dependencies to install or update

### Upload Error Log Content

2024-01-06 21:56:13,806 WARNING  Parsing attempt #3 failed: unexpected character after line continuation character (<unknown>, line 1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/baehyoseong/Library/Caches/pypoetry/virtualenvs/agpt-8COBGpkL-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/baehyoseong/Library/Caches/pypoetry/virtualenvs/agpt-8COBGpkL-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/baehyoseong/Library/Caches/pypoetry/virtualenvs/agpt-8COBGpkL-py3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/baehyoseong/Library/Caches/pypoetry/virtualenvs/agpt-8COBGpkL-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/baehyoseong/Library/Caches/pypoetry/virtualenvs/agpt-8COBGpkL-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/baehyoseong/PycharmProjects/AutoGPT/autogpts/autogpt/autogpt/app/cli.py", line 177, in run
    run_auto_gpt(
  File "/Users/baehyoseong/PycharmProjects/AutoGPT/autogpts/autogpt/autogpt/core/runner/client_lib/utils.py", line 60, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/baehyoseong/PycharmProjects/AutoGPT/autogpts/autogpt/autogpt/app/main.py", line 292, in run_auto_gpt
    await run_interaction_loop(agent)
  File "/Users/baehyoseong/PycharmProjects/AutoGPT/autogpts/autogpt/autogpt/app/main.py", line 489, in run_interaction_loop
    ) = await agent.propose_action()
  File "/Users/baehyoseong/PycharmProjects/AutoGPT/autogpts/autogpt/autogpt/agents/features/watchdog.py", line 36, in propose_action
    command_name, command_args, thoughts = await super(
  File "/Users/baehyoseong/PycharmProjects/AutoGPT/autogpts/autogpt/autogpt/agents/base.py", line 251, in propose_action
    response = await self.llm_provider.create_chat_completion(
  File "/Users/baehyoseong/PycharmProjects/AutoGPT/autogpts/autogpt/autogpt/core/resource/model_providers/openai.py", line 389, in create_chat_completion
    parsed_response = completion_parser(response_message)
  File "/Users/baehyoseong/PycharmProjects/AutoGPT/autogpts/autogpt/autogpt/agents/base.py", line 260, in <lambda>
    completion_parser=lambda r: self.parse_and_process_response(
  File "/Users/baehyoseong/PycharmProjects/AutoGPT/autogpts/autogpt/autogpt/agents/agent.py", line 188, in parse_and_process_response
    ) = self.prompt_strategy.parse_response_content(llm_response)
  File "/Users/baehyoseong/PycharmProjects/AutoGPT/autogpts/autogpt/autogpt/agents/prompt_strategies/one_shot.py", line 394, in parse_response_content
    assistant_reply_dict = extract_dict_from_response(response["content"])
  File "/Users/baehyoseong/PycharmProjects/AutoGPT/autogpts/autogpt/autogpt/json_utils/utilities.py", line 29, in extract_dict_from_response
    result = ast.literal_eval(response_content)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    {\n  name: 'LottoSelector',\n  components: {\n    // Components will be imported here\n  },\n}
      ^
SyntaxError: unexpected character after line continuation character

**Comment by tdergouzi** [comment]
I got the same issue, waiting for response. Thanks for your work.

**Comment by bhsbhs235** [comment]
> I got the same issue, waiting for response. Thanks for your work.
Please be sure to reply once it is resolved. Thank you

**Comment by chenchen333-dev** [comment]
没有requirements.txt文件

**Comment by bhsbhs235** [comment]
> 没有requirements.txt文件

Hasn't it changed to running setup.sh recently?

**Comment by bhsbhs235** [comment]
> > 没有requirements.txt文件
> 
> Hasn't it changed to running setup.sh recently?

I ran the setup file
