### ISSUE TITLE
I'm following the quickstart guide and it says setup.sh doesn't exist

### ISSUE THREAD

**Issue by repryty** [Significant-Gravitas/AutoGPT#6734]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I'm using a translator, so please excuse any unnatural sentences.

I was following [the quickstart guide](https://github.com/Significant-Gravitas/AutoGPT/blob/master/QUICKSTART.md) and when I ran `./run setup.sh`, it stopped with the following error.

`Traceback (most recent call last):
  File "/mnt/c/Users/LG/Documents/GitHub/AutoGPT/cli.py", line 893, in <module>
    cli()
  File "/home/reep/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/reep/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/reep/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/reep/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/reep/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/c/Users/LG/Documents/GitHub/AutoGPT/cli.py", line 52, in setup
    subprocess.check_call([setup_script], cwd=script_dir)
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/LG/Documents/GitHub/AutoGPT/setup.sh'`

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/62415785/a9aeae87-9eab-4d9c-a655-705fbc57447a)

Also, the search results kept telling me to install requirements.txt, but I couldn't find it.

**Comment by MrCredible** [comment]
if you are on windows, then you need to use dos2unix on the run and setup.sh scripts

**Comment by davectr** [comment]
I have this exact same problem.  The dos2unix solution doesn't seem to work.  

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/13407813/d4ddeaa7-4650-4937-977b-940f93aa6c30)

**Comment by MrCredible** [comment]
The instructions could use an update.  You need to use dos2unix for setup, run, and run_benchmark in each agent you create.

**Comment by expeditionist-cj** [comment]
I also encountered the same problem, I typed dos2unix setup.sh and then type ./run setup ,then it's ok.
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/53296987/e8879048-a92b-4573-970b-7e7d58d4475a)
