### ISSUE TITLE
Cannot use custom endpoint

### ISSUE THREAD

**Issue by marufmoinuddin** [Significant-Gravitas/AutoGPT#6750]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Prompt

### Describe your issue.

I have successfully reached the prompt page. but giving any prompt, even saying 'hi' shows this error. how to solve it?

`[2024-01-23 16:06:23,099] [forge.sdk.routes.agent_protocol] [ERROR]     ❌  Error whilst trying to create a task: input='hi' additional_input=None
Traceback (most recent call last):
  File "/home/maruf/.cache/pypoetry/virtualenvs/agpt-hfMNywQ2-py3.10/lib/python3.10/site-packages/forge/sdk/routes/agent_protocol.py", line 86, in create_agent_task
    task_request = await agent.create_task(task_request)
  File "/mnt/Storage/maruf/git/AutoGPT/autogpts/autogpt/autogpt/app/agent_protocol_server.py", line 125, in create_task
    task_agent = await generate_agent_for_task(
  File "/mnt/Storage/maruf/git/AutoGPT/autogpts/autogpt/autogpt/agent_factory/generators.py", line 20, in generate_agent_for_task
    ai_profile, task_directives = await generate_agent_profile_for_task(
  File "/mnt/Storage/maruf/git/AutoGPT/autogpts/autogpt/autogpt/agent_factory/profile_generator.py", line 253, in generate_agent_profile_for_task
    ai_profile, ai_directives = agent_profile_generator.parse_response_content(output)
  File "/mnt/Storage/maruf/git/AutoGPT/autogpts/autogpt/autogpt/agent_factory/profile_generator.py", line 202, in parse_response_content
    raise ValueError(
ValueError: LLM did not call create_agent function; agent profile creation failed`

**Comment by Wladastic** [comment]
I am currently experiencing the same issue when testing with oobabooga/text generation webui API extension.
This is due to Auto-GPT expecting your API to use function calling.
Although you can turn it off in the .env it still tries to use function calling.
