### ISSUE TITLE
should upgrade dependency for multidict when python3.12

### ISSUE THREAD

**Issue by sydowma** [Significant-Gravitas/AutoGPT#7132]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I got an error when I setup autoGPT
I am use python3.12 version, I found there's an dependency block that we need to upgrade multidict to 6.0.5 to compatible python3.12
```
  at venv/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with multidict (6.0.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "multidict (==6.0.4)"'.
```

**Comment by sydowma** [comment]
for thinc
the autoGPT should upgrade to 8.2.1 up
https://github.com/explosion/thinc/releases/tag/v8.2.1

**Comment by sydowma** [comment]
When I switched to python3.11 it also failed
 - Installing vcrpy (5.1.0 bfd15f9): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  Traceback (most recent call last):
    File "/Users/oker/github/download/AutoGPT/autogpts/autogpt/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/oker/github/download/AutoGPT/autogpts/autogpt/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/oker/github/download/AutoGPT/autogpts/autogpt/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
      backend = _build_backend()
                ^^^^^^^^^^^^^^^^
    File "/Users/oker/github/download/AutoGPT/autogpts/autogpt/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 74, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen os>", line 679, in __getitem__
  KeyError: 'PEP517_BUILD_BACKEND'


  at venv/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
  - Downgrading virtualenv (20.26.1 -> 20.25.0)
  - Installing webdriver-manager (4.0.1)
