### ISSUE TITLE
Directory /Users/macmini/AutoGPT/agents/benchmark for agbenchmark does not seem to be a Python package

### ISSUE THREAD

**Issue by wesoly1977** [Significant-Gravitas/AutoGPT#7289]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4(32k)

### Which area covers your issue best?

Documentation

### Describe your issue.

Directory /Users/macmini/AutoGPT/agents/benchmark for agbenchmark does not seem to be a Python package
Setup completed successfully.

⌛ (Re)starting agent 'wesoly'...
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Directory /Users/macmini/AutoGPT/agents/benchmark for agbenchmark does not seem to be a Python package
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/macmini/AutoGPT/agents/Wesoly/forge/__main__.py", line 4, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'
Traceback (most recent call last):
  File "/Users/macmini/AutoGPT/cli.py", line 506, in <module>
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macmini/AutoGPT/cli.py", line 160, in start
    wait_until_conn_ready(8000)
  File "/Users/macmini/AutoGPT/cli.py", line 502, in wait_until_conn_ready
    raise TimeoutError(f"Port {port} did not open within {timeout} seconds")
TimeoutError: Port 8000 did not open within 60 seconds

### Upload Activity Log Content

Directory /Users/macmini/AutoGPT/agents/benchmark for agbenchmark does not seem to be a Python package
Setup completed successfully.

⌛ (Re)starting agent 'wesoly'...
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Directory /Users/macmini/AutoGPT/agents/benchmark for agbenchmark does not seem to be a Python package
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/macmini/AutoGPT/agents/Wesoly/forge/__main__.py", line 4, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'
Traceback (most recent call last):
  File "/Users/macmini/AutoGPT/cli.py", line 506, in <module>
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macmini/AutoGPT/cli.py", line 160, in start
    wait_until_conn_ready(8000)
  File "/Users/macmini/AutoGPT/cli.py", line 502, in wait_until_conn_ready
    raise TimeoutError(f"Port {port} did not open within {timeout} seconds")
TimeoutError: Port 8000 did not open within 60 seconds

**Comment by Swiftyos** [comment]
This is fixed in master branch.

Please `git pull` the latest version to resolve this issue

**Comment by codingyesiamalway** [comment]
had the same issue today. run script does not seem to work for me.
