### ISSUE TITLE
Prisma Generate throwing error when installing Prisma CLI

### ISSUE THREAD

**Issue by devenkher** [Significant-Gravitas/AutoGPT#7748]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Master (branch)

### What LLM Provider do you use?

Other (detail in issue)

### Which area covers your issue best?

Installation and setup

### What commit or version are you using?

56ce7ac628f40dc9775a5a230cfab3711950cda2

### Describe your issue.

Trying to run AutoGPT server. As such trying to install the pre-requisite by running the commands mentioned under rnd/autogtp_server/README.md file. The command `"poetry run prisma generate"` does not run and throws error when trying to install Prisma CLI

Following is the error I see on the screen
```
error: poethepoet plugin encountered an error. Set DEBUG_POE_PLUGIN=1 for details.
Installing Prisma CLI
An error ocurred while installing the Prisma CLI; npm install log: npm error code 1
npm error path \\wsl.localhost\Ubuntu\home\deven\.cache\prisma-python\binaries\5.11.0\efd2449663b3d73d637ea1fd226bafbcf45b3102\node_modules\prisma
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/preinstall-entry.js
npm error '\\wsl.localhost\Ubuntu\home\deven\.cache\prisma-python\binaries\5.11.0\efd2449663b3d73d637ea1fd226bafbcf45b3102\node_modules\prisma'
npm error CMD.EXE was started with the above path as the current directory.
npm error UNC paths are not supported.  Defaulting to Windows directory.
npm error node:internal/modules/cjs/loader:1148
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module 'C:\Windows\scripts\preinstall-entry.js'
npm error     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
npm error     at Module._load (node:internal/modules/cjs/loader:986:27)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
npm error     at node:internal/main/run_main_module:28:49 {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: []
npm error }
npm error
npm error Node.js v20.14.0

npm error A complete log of this run can be found in: C:\Users\Deven.K\AppData\Local\npm-cache\_logs\2024-08-08T08_44_46_449Z-debug-0.log

Traceback (most recent call last):
  File "/mnt/d/AutoGPT/rnd/autogpt_server/.venv/bin/prisma", line 8, in <module>
    sys.exit(main())
  File "/mnt/d/AutoGPT/rnd/autogpt_server/.venv/lib/python3.10/site-packages/prisma/cli/cli.py", line 37, in main
    sys.exit(prisma.run(args[1:]))
  File "/mnt/d/AutoGPT/rnd/autogpt_server/.venv/lib/python3.10/site-packages/prisma/cli/prisma.py", line 35, in run
    entrypoint = ensure_cached().entrypoint
  File "/mnt/d/AutoGPT/rnd/autogpt_server/.venv/lib/python3.10/site-packages/prisma/cli/prisma.py", line 99, in ensure_cached
    proc.check_returncode()
  File "/usr/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/mnt/c/Program Files/nodejs/npm', 'install', 'prisma@5.11.0']' returned non-zero exit status 1.
```
Following is the error log contents of 2024-08-08T08_44_46_449Z-debug-0.log
```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@10.7.0
2 info using node@v20.14.0
3 silly config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc
4 silly config:load:file:\\wsl.localhost\Ubuntu\home\deven\.cache\prisma-python\binaries\5.11.0\efd2449663b3d73d637ea1fd226bafbcf45b3102\.npmrc
5 silly config:load:file:C:\Users\Deven.K\.npmrc
6 silly config:load:file:C:\Users\Deven.K\AppData\Roaming\npm\etc\npmrc
7 verbose title npm install prisma@5.11.0
8 verbose argv "install" "prisma@5.11.0"
9 verbose logfile logs-max:10 dir:C:\Users\Deven.K\AppData\Local\npm-cache\_logs\2024-08-08T08_44_46_449Z-
10 verbose logfile C:\Users\Deven.K\AppData\Local\npm-cache\_logs\2024-08-08T08_44_46_449Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 silly idealTree buildDeps
14 silly fetch manifest prisma@5.11.0
15 http fetch GET 200 https://registry.npmjs.org/prisma 411ms (cache revalidated)
16 silly placeDep ROOT prisma@5.11.0 OK for: prisma-binaries@1.0.0 want: 5.11.0
17 silly fetch manifest @prisma/engines@5.11.0
18 http fetch GET 200 https://registry.npmjs.org/@prisma%2fengines 449ms (cache revalidated)
19 silly placeDep ROOT @prisma/engines@5.11.0 OK for: prisma@5.11.0 want: 5.11.0
20 silly fetch manifest @prisma/debug@5.11.0
21 silly fetch manifest @prisma/fetch-engine@5.11.0
22 silly fetch manifest @prisma/get-platform@5.11.0
23 silly fetch manifest @prisma/engines-version@5.11.0-15.efd2449663b3d73d637ea1fd226bafbcf45b3102
24 http fetch GET 200 https://registry.npmjs.org/@prisma%2fget-platform 118ms (cache revalidated)
25 http fetch GET 200 https://registry.npmjs.org/@prisma%2fengines-version 562ms (cache revalidated)
26 http fetch GET 200 https://registry.npmjs.org/@prisma%2fdebug 1168ms (cache revalidated)
27 http fetch GET 200 https://registry.npmjs.org/@prisma%2ffetch-engine 1693ms (cache revalidated)
28 silly placeDep ROOT @prisma/debug@5.11.0 OK for: @prisma/engines@5.11.0 want: 5.11.0
29 silly placeDep ROOT @prisma/engines-version@5.11.0-15.efd2449663b3d73d637ea1fd226bafbcf45b3102 OK for: @prisma/engines@5.11.0 want: 5.11.0-15.efd2449663b3d73d637ea1fd226bafbcf45b3102
30 silly placeDep ROOT @prisma/fetch-engine@5.11.0 OK for: @prisma/engines@5.11.0 want: 5.11.0
31 silly placeDep ROOT @prisma/get-platform@5.11.0 OK for: @prisma/engines@5.11.0 want: 5.11.0
32 silly reify moves {}
33 silly audit bulk request {
33 silly audit   prisma: [ '5.11.0' ],
33 silly audit   '@prisma/engines': [ '5.11.0' ],
33 silly audit   '@prisma/debug': [ '5.11.0' ],
33 silly audit   '@prisma/engines-version': [ '5.11.0-15.efd2449663b3d73d637ea1fd226bafbcf45b3102' ],
33 silly audit   '@prisma/fetch-engine': [ '5.11.0' ],
33 silly audit   '@prisma/get-platform': [ '5.11.0' ]
33 silly audit }
34 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 264ms
35 silly audit report {}
36 info run prisma@5.11.0 preinstall node_modules/prisma node scripts/preinstall-entry.js
37 info run prisma@5.11.0 preinstall { code: 1, signal: null }
38 verbose stack Error: command failed
38 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
38 verbose stack     at ChildProcess.emit (node:events:519:28)
38 verbose stack     at maybeClose (node:internal/child_process:1105:16)
38 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
39 verbose pkgid prisma@5.11.0
40 verbose cwd \\wsl.localhost\Ubuntu\home\deven\.cache\prisma-python\binaries\5.11.0\efd2449663b3d73d637ea1fd226bafbcf45b3102
41 verbose Windows_NT 10.0.22631
42 verbose node v20.14.0
43 verbose npm  v10.7.0
44 error code 1
45 error path \\wsl.localhost\Ubuntu\home\deven\.cache\prisma-python\binaries\5.11.0\efd2449663b3d73d637ea1fd226bafbcf45b3102\node_modules\prisma
46 error command failed
47 error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/preinstall-entry.js
48 error '\\wsl.localhost\Ubuntu\home\deven\.cache\prisma-python\binaries\5.11.0\efd2449663b3d73d637ea1fd226bafbcf45b3102\node_modules\prisma'
48 error CMD.EXE was started with the above path as the current directory.
48 error UNC paths are not supported.  Defaulting to Windows directory.
48 error node:internal/modules/cjs/loader:1148
48 error   throw err;
48 error   ^
48 error
48 error Error: Cannot find module 'C:\Windows\scripts\preinstall-entry.js'
48 error     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
48 error     at Module._load (node:internal/modules/cjs/loader:986:27)
48 error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
48 error     at node:internal/main/run_main_module:28:49 {
48 error   code: 'MODULE_NOT_FOUND',
48 error   requireStack: []
48 error }
48 error
48 error Node.js v20.14.0
49 verbose exit 1
50 verbose code 1
51 silly unfinished npm timer reify 1723106687094
52 silly unfinished npm timer reify:build 1723106690926
53 silly unfinished npm timer build 1723106690926
54 silly unfinished npm timer build:deps 1723106690927
55 silly unfinished npm timer build:run:preinstall 1723106690928
56 silly unfinished npm timer build:run:preinstall:node_modules/prisma 1723106690928
57 error A complete log of this run can be found in: C:\Users\Deven.K\AppData\Local\npm-cache\_logs\2024-08-08T08_44_46_449Z-debug-0.log

```

**Comment by devenkher** [comment]
The issue occurs in Windows WSL
Resolved this.
If you are running it on Windows and VSCode do the following
1. Create venv in VS Code using Python Vent
2. Activate the virtual environment from within the VS Code
3. Follow steps in README.md under rnd/autogpt_server/ and this should resolve within the Windows environment

Hope that helps others
