### ISSUE TITLE
db connection manager takes longer to startup than the executors

### ISSUE THREAD

**Issue by Torantulino** [Significant-Gravitas/AutoGPT#9111]

**Comment by LingXuanYin** [comment]
同样的问题，有快速的解决方案吗，我现在根本没法运行任何工作流
补充一下我在docker的日志中捕捉到的报错信息
`2025-02-05 20:59:42 supabase-analytics              | 
2025-02-05 20:59:42 supabase-analytics              | 12:59:42.707 [info] Logs last second!
2025-02-05 20:59:43 rest_server-1                   | 2025-02-05 12:59:43,620 INFO  [PID-1|THREAD-329|AgentServer|Pyro-d9ae649e-d706-46f6-9e5c-2c61013ef37d] Connecting to [ExecutionManager] started...
2025-02-05 20:59:43 rest_server-1                   | 2025-02-05 12:59:43,627 INFO  [PID-1|THREAD-329|AgentServer|Pyro-d9ae649e-d706-46f6-9e5c-2c61013ef37d] Connecting to [ExecutionManager] completed successfully.
2025-02-05 20:59:43 rest_server-1                   | INFO:     172.19.0.1:55082 - "GET /api/executions HTTP/1.1" 200 OK
2025-02-05 20:59:43 executor-1                      | 2025-02-05 12:59:43,635 ERROR  Error in get_graph: All connection attempts failed
2025-02-05 20:59:43 executor-1                      | Traceback (most recent call last):
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
2025-02-05 20:59:43 executor-1                      |     yield
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
2025-02-05 20:59:43 executor-1                      |     resp = await self._pool.handle_async_request(req)
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
2025-02-05 20:59:43 executor-1                      |     raise exc from None
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
2025-02-05 20:59:43 executor-1                      |     response = await connection.handle_async_request(
2025-02-05 20:59:43 executor-1                      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
2025-02-05 20:59:43 executor-1                      |     raise exc
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 78, in handle_async_request
2025-02-05 20:59:43 executor-1                      |     stream = await self._connect(request)
2025-02-05 20:59:43 executor-1                      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 124, in _connect
2025-02-05 20:59:43 executor-1                      |     stream = await self._network_backend.connect_tcp(**kwargs)
2025-02-05 20:59:43 executor-1                      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
2025-02-05 20:59:43 executor-1                      |     return await self._backend.connect_tcp(
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 113, in connect_tcp
2025-02-05 20:59:43 executor-1                      |     with map_exceptions(exc_map):
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
2025-02-05 20:59:43 executor-1                      |     self.gen.throw(typ, value, traceback)
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2025-02-05 20:59:43 executor-1                      |     raise to_exc(exc) from exc
2025-02-05 20:59:43 executor-1                      | httpcore.ConnectError: All connection attempts failed
2025-02-05 20:59:43 executor-1                      | 
2025-02-05 20:59:43 executor-1                      | The above exception was the direct cause of the following exception:
2025-02-05 20:59:43 executor-1                      | 
2025-02-05 20:59:43 executor-1                      | Traceback (most recent call last):
2025-02-05 20:59:43 executor-1                      |   File "/app/autogpt_platform/backend/backend/util/service.py", line 62, in wrapper
2025-02-05 20:59:43 executor-1                      |     return func(*args, **kwargs)
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/app/autogpt_platform/backend/backend/executor/database.py", line 57, in wrapper
2025-02-05 20:59:43 executor-1                      |     res = self.run_and_wait(coroutine)
2025-02-05 20:59:43 executor-1                      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/app/autogpt_platform/backend/backend/util/service.py", line 142, in run_and_wait
2025-02-05 20:59:43 executor-1                      |     return future.result()
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
2025-02-05 20:59:43 executor-1                      |     return self.__get_result()
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
2025-02-05 20:59:43 executor-1                      |     raise self._exception
2025-02-05 20:59:43 executor-1                      |   File "/app/autogpt_platform/backend/backend/data/graph.py", line 558, in get_graph
2025-02-05 20:59:43 executor-1                      |     graph = await AgentGraph.prisma().find_first(
2025-02-05 20:59:43 executor-1                      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/prisma/actions.py", line 1559, in find_first
2025-02-05 20:59:43 executor-1                      |     resp = await self._client._execute(
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/prisma/_base_client.py", line 543, in _execute
2025-02-05 20:59:43 executor-1                      |     return await self._engine.query(builder.build(), tx_id=self._tx_id)
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/prisma/engine/_query.py", line 402, in query
2025-02-05 20:59:43 executor-1                      |     return await self.request(
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/prisma/engine/_http.py", line 217, in request
2025-02-05 20:59:43 rest_server-1                   | INFO:     172.19.0.1:55070 - "GET /api/library/agents HTTP/1.1" 200 OK
2025-02-05 20:59:43 executor-1                      |     response = await self.session.request(method, url, **kwargs)
2025-02-05 20:59:43 executor-1                      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/prisma/_async_http.py", line 26, in request
2025-02-05 20:59:43 executor-1                      |     return Response(await self.session.request(method, url, **kwargs))
2025-02-05 20:59:43 executor-1                      |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1585, in request
2025-02-05 20:59:43 executor-1                      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/httpx.py", line 142, in send
2025-02-05 20:59:43 executor-1                      |     rv = await real_send(self, request, **kwargs)
2025-02-05 20:59:43 executor-1                      |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1674, in send
2025-02-05 20:59:43 executor-1                      |     response = await self._send_handling_auth(
2025-02-05 20:59:43 executor-1                      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
2025-02-05 20:59:43 executor-1                      |     response = await self._send_handling_redirects(
2025-02-05 20:59:43 executor-1                      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
2025-02-05 20:59:43 executor-1                      |     response = await self._send_single_request(request)
2025-02-05 20:59:43 executor-1                      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1776, in _send_single_request
2025-02-05 20:59:43 executor-1                      |     response = await transport.handle_async_request(request)
2025-02-05 20:59:43 executor-1                      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
2025-02-05 20:59:43 executor-1                      |     with map_httpcore_exceptions():
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
2025-02-05 20:59:43 executor-1                      |     self.gen.throw(typ, value, traceback)
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
2025-02-05 20:59:43 executor-1                      |     raise mapped_exc(message) from exc
2025-02-05 20:59:43 executor-1                      | httpx.ConnectError: All connection attempts failed
2025-02-05 20:59:43 executor-1                      | 2025-02-05 12:59:43,674 ERROR  Error in add_execution: unsupported serialized class: httpx.ConnectError
2025-02-05 20:59:43 executor-1                      | Traceback (most recent call last):
2025-02-05 20:59:43 executor-1                      |   File "/app/autogpt_platform/backend/backend/util/service.py", line 62, in wrapper
2025-02-05 20:59:43 executor-1                      |     return func(*args, **kwargs)
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/app/autogpt_platform/backend/backend/executor/manager.py", line 810, in add_execution
2025-02-05 20:59:43 executor-1                      |     graph: GraphModel | None = self.db_client.get_graph(
2025-02-05 20:59:43 executor-1                      |                                ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/Pyro5/client.py", line 510, in __call__
2025-02-05 20:59:43 executor-1                      |     return self.__send(self.__name, args, kwargs)
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/Pyro5/client.py", line 268, in _pyroInvoke
2025-02-05 20:59:43 executor-1                      |     data = serializer.loads(msg.data)
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/Pyro5/serializers.py", line 290, in loads
2025-02-05 20:59:43 executor-1                      |     return self.recreate_classes(serpent.loads(data))
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/Pyro5/serializers.py", line 256, in recreate_classes
2025-02-05 20:59:43 executor-1                      |     return self.dict_to_class(literal)
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/Pyro5/serializers.py", line 309, in dict_to_class
2025-02-05 20:59:43 executor-1                      |     return super(SerpentSerializer, cls).dict_to_class(data)
2025-02-05 20:59:43 executor-1                      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05 20:59:43 executor-1                      |   File "/usr/local/lib/python3.11/site-packages/Pyro5/serializers.py", line 235, in dict_to_class
2025-02-05 20:59:43 executor-1                      |     raise errors.SerializeError("unsupported serialized class: " + classname)
2025-02-05 20:59:43 executor-1                      | Pyro5.errors.SerializeError: unsupported serialized class: httpx.ConnectError
2025-02-05 20:59:43 rest_server-1                   | INFO:     172.19.0.1:55064 - "POST /api/graphs/15b838d6-9ed5-4c86-8674-a651327b40b5/execute HTTP/1.1" 400 Bad Request
2025-02-05 20:59:43 supabase-analytics              | 
2025-02-05 20:59:43 supabase-analytics              | 12:59:43.709 [info] All logs logged!`
